spring:
  application:
    name: payroll
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/zynctra_payroll
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

server:
  port: 8003
  servlet:
    context-path: /payroll
