package com.zynctra.securityadmin.audit;

public enum AuditAction {
    POLICY_CREATED, POLICY_UPDATED, POLICY_VERSIONED, POLICY_APPROVED,
    POLICY_DELETED, POLICY_ACTIVATED, POLICY_DEACTIVATED, POLICY_ACCESSED,
    POLICY_EXPORTED, POLICY_IMPORT_ATTEMPT, SECURITY_EVENT_LOGGED,
    UNAUTHORIZED_ACCESS_ATTEMPT, RATE_LIMIT_EXCEEDED, DANGEROUS_CONTENT_BLOCKED
}